package com.mycompany.supermarket_project;

import com.mycompany.supermarket_project.model.Product;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MarketingForm extends javax.swing.JFrame {

    public MarketingForm() {
        initComponents();
        expireDateChooser.setDate(new Date());
        productQuantityInput.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        addOffersPnl = new javax.swing.JPanel();
        pructIdLbl = new javax.swing.JLabel();
        offerLbl = new javax.swing.JLabel();
        productIDInput = new javax.swing.JTextField();
        offerInput = new javax.swing.JTextField();
        addOfferBtn = new javax.swing.JButton();
        reportingPnl = new javax.swing.JPanel();
        productNameLbl = new javax.swing.JLabel();
        quantityLbl = new javax.swing.JLabel();
        expireDateLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        productNameInput = new javax.swing.JTextField();
        productQuantityInput = new javax.swing.JTextField();
        expireDateChooser = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchResultTable = new javax.swing.JTable();
        searchBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        chngInfoBtn = new javax.swing.JMenu();
        signOutBtn = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Marketing Panel");

        pructIdLbl.setText("Product Id");

        offerLbl.setText("Offer (%)");

        addOfferBtn.setText("Add Offer");
        addOfferBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addOfferBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout addOffersPnlLayout = new javax.swing.GroupLayout(addOffersPnl);
        addOffersPnl.setLayout(addOffersPnlLayout);
        addOffersPnlLayout.setHorizontalGroup(
            addOffersPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addOffersPnlLayout.createSequentialGroup()
                .addGroup(addOffersPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addOffersPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(addOffersPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pructIdLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(offerLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(addOffersPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(offerInput, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addOffersPnlLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(addOfferBtn)))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        addOffersPnlLayout.setVerticalGroup(
            addOffersPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addOffersPnlLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(addOffersPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pructIdLbl)
                    .addComponent(productIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addOffersPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(offerLbl)
                    .addComponent(offerInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(addOfferBtn)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Offers   ", addOffersPnl);

        productNameLbl.setText("Product Name");

        quantityLbl.setText("Quantity (More than)");

        expireDateLbl.setText("Expire Date (before)");

        expireDateChooser.setDateFormatString("yyyy-MM-dd");

        searchResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Quantity", "Min Quantity", "Price", "Expire Date", "Offer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        searchResultTable.setMinimumSize(new java.awt.Dimension(50, 50));
        searchResultTable.setShowGrid(true);
        jScrollPane1.setViewportView(searchResultTable);

        searchBtn.setText("Search");
        searchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout reportingPnlLayout = new javax.swing.GroupLayout(reportingPnl);
        reportingPnl.setLayout(reportingPnlLayout);
        reportingPnlLayout.setHorizontalGroup(
            reportingPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportingPnlLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(reportingPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reportingPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(reportingPnlLayout.createSequentialGroup()
                        .addGroup(reportingPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(expireDateLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(quantityLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(productNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(reportingPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(expireDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(reportingPnlLayout.createSequentialGroup()
                                .addGroup(reportingPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(productNameInput, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                    .addComponent(productQuantityInput, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(searchBtn)
                                .addGap(86, 86, 86)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        reportingPnlLayout.setVerticalGroup(
            reportingPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportingPnlLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportingPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(reportingPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productQuantityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(reportingPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(expireDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expireDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Search Products", reportingPnl);

        chngInfoBtn.setText("Change My Information");
        chngInfoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chngInfoBtnMouseClicked(evt);
            }
        });
        jMenuBar1.add(chngInfoBtn);

        signOutBtn.setText("Sign Out");
        signOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signOutBtnMouseClicked(evt);
            }
        });
        jMenuBar1.add(signOutBtn);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signOutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOutBtnMouseClicked
        // TODO add your handling code here:
        Supermarket.signout();
        this.dispose();
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_signOutBtnMouseClicked

    private void chngInfoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chngInfoBtnMouseClicked
        // TODO add your handling code here:
        new ChangeOwnInfoForm().setVisible(true);
    }//GEN-LAST:event_chngInfoBtnMouseClicked

    private void searchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseClicked
        // TODO add your handling code here:
        List<Product> searchProductList=new ArrayList<>();
        if(!utility.Utilities.isValidInteger(this, productQuantityInput.getText())){
            return;
        }
        for (int i = 0; i < Supermarket.productList.size(); i++) {
            if(Supermarket.productList.get(i).getName().toLowerCase().contains(productNameInput.getText().toLowerCase())&&
                   Supermarket.productList.get(i).getQuantity()>=Integer.parseInt(productQuantityInput.getText())&&
                    Supermarket.productList.get(i).getExpireDate().before(expireDateChooser.getDate())){
                searchProductList.add(Supermarket.productList.get(i));
            }
        }
        if(searchProductList.isEmpty())JOptionPane.showMessageDialog(this, "no Result");
        addDataToTable(searchProductList);
    }//GEN-LAST:event_searchBtnMouseClicked

    public boolean validOffer(){
        try{
            float offer=Float.parseFloat(offerInput.getText());
            if(offer>=0&&offer<=100){
                return true;
            }
            else {
                JOptionPane.showMessageDialog(this, "offer should be 0 <=offer<= 100");
                return false;
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "offer should be number");
            return false;
        }
    }
    
    private void addOfferBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addOfferBtnMouseClicked
        // TODO add your handling code here:
        if(!utility.Utilities.isValidLong(this, productIDInput.getText())||
           !utility.Utilities.isValidInteger(this, offerInput.getText())||
           !validOffer()){
            return;
        }
        for (int i = 0; i < Supermarket.productList.size(); i++) {
            if(Supermarket.productList.get(i).getId()==Long.parseLong(productIDInput.getText())){
                Supermarket.productList.get(i).setOffer(Float.parseFloat(offerInput.getText()));
                utility.Utilities.saveProductsToFile();
                JOptionPane.showMessageDialog(this, "Offer Added Successfully");
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "This Product Id isn't available");
    }//GEN-LAST:event_addOfferBtnMouseClicked

    private void addDataToTable(List<Product> productList){ 
        DefaultTableModel tableModel=(DefaultTableModel)searchResultTable.getModel();
        tableModel.setRowCount(0);
        Object rowData[]=new Object[7];
        for (int i = 0; i < productList.size(); i++) {
            rowData[0]=productList.get(i).getId();
            rowData[1]=productList.get(i).getName();
            rowData[2]=productList.get(i).getQuantity();
            rowData[3]=productList.get(i).getMinQuantity();
            rowData[4]=productList.get(i).getPrice();
            rowData[5]=productList.get(i).getExpireDate().toString();
            rowData[6]=productList.get(i).getOffer();
            tableModel.addRow(rowData);
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarketingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarketingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarketingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarketingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarketingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOfferBtn;
    private javax.swing.JPanel addOffersPnl;
    private javax.swing.JMenu chngInfoBtn;
    private com.toedter.calendar.JDateChooser expireDateChooser;
    private javax.swing.JLabel expireDateLbl;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField offerInput;
    private javax.swing.JLabel offerLbl;
    private javax.swing.JTextField productIDInput;
    private javax.swing.JTextField productNameInput;
    private javax.swing.JLabel productNameLbl;
    private javax.swing.JTextField productQuantityInput;
    private javax.swing.JLabel pructIdLbl;
    private javax.swing.JLabel quantityLbl;
    private javax.swing.JPanel reportingPnl;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTable searchResultTable;
    private javax.swing.JMenu signOutBtn;
    // End of variables declaration//GEN-END:variables
}
