package com.mycompany.supermarket_project;

import com.mycompany.supermarket_project.model.Order;
import com.mycompany.supermarket_project.model.OrderItem;
import com.mycompany.supermarket_project.model.Product;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class SalesForm extends javax.swing.JFrame {

    private List<OrderItem> orderItemsList=new ArrayList<>();
    public SalesForm() {
        initComponents();
        orderPriceShow.setText("0");
        setOrderNumber();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        productIdInput = new javax.swing.JTextField();
        quantityInput = new javax.swing.JTextField();
        productIdLbl = new javax.swing.JLabel();
        quantityLbl = new javax.swing.JLabel();
        addToOrderBtn = new javax.swing.JButton();
        submitOrder = new javax.swing.JButton();
        searchOrderBtn = new javax.swing.JButton();
        deleteOrderBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderResults = new javax.swing.JTable();
        clrFormBtn = new javax.swing.JButton();
        OrderNoShow = new javax.swing.JTextField();
        orderPriceShow = new javax.swing.JTextField();
        orderNoLbl = new javax.swing.JLabel();
        orderPriceLbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        searchByIdBtn = new javax.swing.JButton();
        searchByNameBtn = new javax.swing.JButton();
        listAllProductsBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchResultTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        chngInfoBtn = new javax.swing.JMenu();
        signOutBtn1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sales Panel");

        productIdLbl.setText("Product Id");

        quantityLbl.setText("Quantity");

        addToOrderBtn.setText("Add To Order");
        addToOrderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addToOrderBtnMouseClicked(evt);
            }
        });

        submitOrder.setText("Submit Order");
        submitOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitOrderMouseClicked(evt);
            }
        });

        searchOrderBtn.setText("Search Order");
        searchOrderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchOrderBtnMouseClicked(evt);
            }
        });

        deleteOrderBtn.setText("Delete Order");
        deleteOrderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteOrderBtnMouseClicked(evt);
            }
        });

        orderResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Id", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orderResults);

        clrFormBtn.setText("Clear");
        clrFormBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clrFormBtnMouseClicked(evt);
            }
        });

        OrderNoShow.setEditable(false);

        orderPriceShow.setEditable(false);

        orderNoLbl.setText("Order No");

        orderPriceLbl.setText("Order Price");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(quantityLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(quantityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(searchOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(deleteOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addToOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(clrFormBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(productIdLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(orderNoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(orderPriceLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(productIdInput, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(OrderNoShow)
                            .addComponent(orderPriceShow))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OrderNoShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderNoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(orderPriceShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(orderPriceLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productIdInput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productIdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantityLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addToOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submitOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(clrFormBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1013, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Orders   ", jPanel2);

        searchByIdBtn.setText("Search By Id");
        searchByIdBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchByIdBtnMouseClicked(evt);
            }
        });

        searchByNameBtn.setText("Search By Name");
        searchByNameBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchByNameBtnMouseClicked(evt);
            }
        });

        listAllProductsBtn.setText("List All Products");
        listAllProductsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listAllProductsBtnMouseClicked(evt);
            }
        });

        searchResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Quantity", "Min Quantity", "Price", "offer", "Expire Date", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        searchResultTable.setMinimumSize(new java.awt.Dimension(50, 50));
        searchResultTable.setShowGrid(true);
        jScrollPane2.setViewportView(searchResultTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchByNameBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listAllProductsBtn)
                    .addComponent(searchByIdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(searchByIdBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchByNameBtn)
                .addGap(18, 18, 18)
                .addComponent(listAllProductsBtn)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );

        jTabbedPane1.addTab("Search   ", jPanel1);

        chngInfoBtn.setText("Change My Information");
        chngInfoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chngInfoBtnMouseClicked(evt);
            }
        });
        jMenuBar1.add(chngInfoBtn);

        signOutBtn1.setText("Sign Out");
        signOutBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signOutBtn1MouseClicked(evt);
            }
        });
        jMenuBar1.add(signOutBtn1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void clearForm(){
        productIdInput.setText("");
        quantityInput.setText("");
        orderItemsList=new ArrayList<>();
        addDataToOrdersTable();
        addToOrderBtn.setEnabled(true);
        submitOrder.setEnabled(true);
        orderPriceShow.setText("0");
        setOrderNumber();
    }
    
    private void signOutBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOutBtn1MouseClicked
        // TODO add your handling code here:
        Supermarket.signout();
        this.dispose();
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_signOutBtn1MouseClicked

    private void setOrderNumber(){
        if(!Supermarket.orderList.isEmpty()){
            OrderNoShow.setText((Supermarket.orderList.get(Supermarket.orderList.size()-1).getOrderId()+1)+"");
        }else{
            OrderNoShow.setText("1");
        }
    }
    
    private void chngInfoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chngInfoBtnMouseClicked
        // TODO add your handling code here:
        new ChangeOwnInfoForm().setVisible(true);
    }//GEN-LAST:event_chngInfoBtnMouseClicked

    private void listAllProductsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listAllProductsBtnMouseClicked
        // TODO add your handling code here:
        addDataToSearchTable(Supermarket.productList);
    }//GEN-LAST:event_listAllProductsBtnMouseClicked

    private void searchByNameBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchByNameBtnMouseClicked
        // TODO add your handling code here:
        String productId=JOptionPane.showInputDialog("Enter Product Name");
        List<Product> searchProductList=new ArrayList<>();
        for (int i = 0; i < Supermarket.productList.size(); i++) {
            if(Supermarket.productList.get(i).getName().toLowerCase().contains(productId.toLowerCase())){
                searchProductList.add(Supermarket.productList.get(i));
            }
        }
        if(searchProductList.isEmpty())JOptionPane.showMessageDialog(this, "no Result");
        else addDataToSearchTable(searchProductList);
    }//GEN-LAST:event_searchByNameBtnMouseClicked

    private void searchByIdBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchByIdBtnMouseClicked
        // TODO add your handling code here:
        String productId=JOptionPane.showInputDialog("Enter Product Id");
        List<Product> searchProductList=new ArrayList<>();
        if(!utility.Utilities.isValidLong(this, productId)){
            return;
        }
        for (int i = 0; i < Supermarket.productList.size(); i++) {
            if(Supermarket.productList.get(i).getId()==Long.parseLong(productId)){
                searchProductList.add(Supermarket.productList.get(i));
            }
        }
        if(searchProductList.isEmpty())JOptionPane.showMessageDialog(this, "no Result");
        else addDataToSearchTable(searchProductList);
    }//GEN-LAST:event_searchByIdBtnMouseClicked

    private void clrFormBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clrFormBtnMouseClicked
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_clrFormBtnMouseClicked

    private void deleteOrderBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteOrderBtnMouseClicked
        // TODO add your handling code here:
        String orderId=JOptionPane.showInputDialog("Enter Order ID");
        if(!utility.Utilities.isValidInteger(this, orderId))return;
        for (int i = 0; i < Supermarket.orderList.size(); i++) {
            if(Supermarket.orderList.get(i).getOrderId()==Long.parseLong(orderId)){
                Supermarket.orderList.remove(i);
                utility.Utilities.saveOrdersToFile();
                JOptionPane.showMessageDialog(this, "Order no "+orderId+" deleted successfully");
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "Order no "+orderId+" not found");
    }//GEN-LAST:event_deleteOrderBtnMouseClicked

    private void searchOrderBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchOrderBtnMouseClicked
        // TODO add your handling code here:
        String orderId=JOptionPane.showInputDialog("Enter Order ID");
        if(!utility.Utilities.isValidInteger(this, orderId))return;
        for (int i = 0; i < Supermarket.orderList.size(); i++) {
            if(Supermarket.orderList.get(i).getOrderId()==Long.parseLong(orderId)){
                orderItemsList=Supermarket.orderList.get(i).getOrderItems();
                addDataToOrdersTable();
                OrderNoShow.setText(orderId);
                orderPriceShow.setText(Supermarket.orderList.get(i).getTotalPrice()+"");
                addToOrderBtn.setEnabled(false);
                submitOrder.setEnabled(false);
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "Order no "+orderId+" not found");
        clearForm();
    }//GEN-LAST:event_searchOrderBtnMouseClicked

    private void submitOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitOrderMouseClicked
        // TODO add your handling code here:
        double orderPrice=0;
        for (int i = 0; i < orderItemsList.size(); i++) {
            orderPrice+=orderItemsList.get(i).getPrice();
            for (int j = 0; j < Supermarket.productList.size(); j++) {
                if(orderItemsList.get(i).getItemId()==Supermarket.productList.get(j).getId()){
                    Supermarket.productList.get(j).setQuantity(Supermarket.productList.get(j).getQuantity()-orderItemsList.get(i).getQuantity());
                }
            }
        }
        Supermarket.orderList.add(new Order(Long.parseLong(OrderNoShow.getText()),orderItemsList,orderPrice));
        utility.Utilities.saveOrdersToFile();
        clearForm();
        JOptionPane.showMessageDialog(this, "order created successfully");
    }//GEN-LAST:event_submitOrderMouseClicked

    private void addToOrderBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addToOrderBtnMouseClicked
        // TODO add your handling code here:
        if(!utility.Utilities.isValidLong(this, productIdInput.getText())||
            !utility.Utilities.isValidInteger(this, quantityInput.getText())){
            return;
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        

        for (int i = 0; i < Supermarket.productList.size(); i++) {//This item isn't added to this order before
            if(Supermarket.productList.get(i).getId()==Long.parseLong(productIdInput.getText())){
                Product product=Supermarket.productList.get(i);
                if(product.getQuantity()<Integer.parseInt(quantityInput.getText())){
                    JOptionPane.showMessageDialog(this, "Quantity isn't enough");
                    return;
                }
                double pricePerItem=product.getPrice()-(product.getOffer()/100)*product.getPrice();
                double priceOfQuantity=Integer.parseInt(quantityInput.getText())*pricePerItem;
                double totalpriceOfOrder=Double.parseDouble(orderPriceShow.getText())+priceOfQuantity;
                orderPriceShow.setText(totalpriceOfOrder+"");
                OrderItem orderItem=new OrderItem(product.getId(), Integer.parseInt(quantityInput.getText()), priceOfQuantity);
                orderItemsList.add(orderItem);
                addDataToOrdersTable();
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "This Product Id isn't available");
    }//GEN-LAST:event_addToOrderBtnMouseClicked

    private void addDataToSearchTable(List<Product> productList){ 
        DefaultTableModel tableModel=(DefaultTableModel)searchResultTable.getModel();
        tableModel.setRowCount(0);
        Object rowData[]=new Object[8];
        for (int i = 0; i < productList.size(); i++) {
            rowData[0]=productList.get(i).getId();
            rowData[1]=productList.get(i).getName();
            rowData[2]=productList.get(i).getQuantity();
            rowData[3]=productList.get(i).getMinQuantity();
            rowData[4]=productList.get(i).getPrice();
            rowData[5]=productList.get(i).getOffer();
            rowData[6]=productList.get(i).getExpireDate().toString();
            rowData[7]=productList.get(i).getDescription();
            tableModel.addRow(rowData);
        }
    }
    
    private void addDataToOrdersTable(){ 
        DefaultTableModel tableModel=(DefaultTableModel)orderResults.getModel();
        tableModel.setRowCount(0);
        Object rowData[]=new Object[3];
        for (int i = 0; i < orderItemsList.size(); i++) {
            rowData[0]=orderItemsList.get(i).getItemId();
            rowData[1]=orderItemsList.get(i).getQuantity();
            rowData[2]=orderItemsList.get(i).getPrice();
            tableModel.addRow(rowData);
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField OrderNoShow;
    private javax.swing.JButton addToOrderBtn;
    private javax.swing.JMenu chngInfoBtn;
    private javax.swing.JButton clrFormBtn;
    private javax.swing.JButton deleteOrderBtn;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton listAllProductsBtn;
    private javax.swing.JLabel orderNoLbl;
    private javax.swing.JLabel orderPriceLbl;
    private javax.swing.JTextField orderPriceShow;
    private javax.swing.JTable orderResults;
    private javax.swing.JTextField productIdInput;
    private javax.swing.JLabel productIdLbl;
    private javax.swing.JTextField quantityInput;
    private javax.swing.JLabel quantityLbl;
    private javax.swing.JButton searchByIdBtn;
    private javax.swing.JButton searchByNameBtn;
    private javax.swing.JButton searchOrderBtn;
    private javax.swing.JTable searchResultTable;
    private javax.swing.JMenu signOutBtn1;
    private javax.swing.JButton submitOrder;
    // End of variables declaration//GEN-END:variables
}
